"use strict";
const { mongoose } = require("../db");

/*
 * We intentionally use `id` (UUID string) as our own primary key field instead of
 * Mongoose's default _id, so JSON payloads match the shape the React frontend already
 * consumes. `_id` is still auto-generated by Mongo but is never sent to clients.
 */

const userSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    email: { type: String, required: true, unique: true, lowercase: true, trim: true, index: true },
    password_hash: { type: String, required: true },
    name: { type: String, required: true },
    role: { type: String, enum: ["student", "supervisor", "admin"], required: true },
    created_at: { type: String, required: true },
  },
  { collection: "users", versionKey: false, strict: false }
);

userSchema.set("toJSON", {
  transform: (_doc, ret) => {
    delete ret._id;
    delete ret.password_hash;
    return ret;
  },
});

module.exports = mongoose.model("User", userSchema);
